### ISSUE TITLE
Test other things than addresses

### ISSUE THREAD

**Issue by nlehuby** [geocoders/geocoder-tester#23]
Would it be relevant to add test in geocoder tester for non point features ?
For instance :

- region : Normandie
- department : Aveyron
- POI that are large area : Parc du Mercantour
- geographical area that are not proper POI or region : Bassin d'Arcachon, Périgord

**Comment by yohanboniface** [comment]
Sure, we could event test for POIs. What's important imho is to correctly structure the data, so it's possible to skip/target some kind of search.
In this case, for example, you would put those test cases in a folder `areas/` and in the correct country/region/city folders, so it's possible to filter them out with `-m "no areas"` or similar.
I guess you would not test for the geographical coordinates though for areas, because it's too vague imho.

**Comment by nlehuby** [comment]
ok :)
